<?php
;
const CONTRIBUTE_FORM_FIELDS = [
    'name' => [
        'label' => 'Restaurant Name',
        'element' => 'input',
        'type' => 'text',
        'required' => true,
        'min_length' => 3,
        'max_length' => 100,
        'placeholder' => 'Enter restaurant name',
        'name' => 'name',
        'id' => 'place-name',
    ],
    'address' => [
        'label' => 'Address',
        'element' => 'input',
        'type' => 'text',
        'required' => true,
        'min_length' => 5,
        'max_length' => 255,
        'placeholder' => 'Enter restaurant address',
        'name' => 'address',
        'id' => 'place-location',
    ],
    'description' => [
        'label' => 'Description',
        'element' => 'textarea',
        'type' => 'textarea',
        'required' => true,
        'min_length' => 10,
        'max_length' => 1000,
        'placeholder' => 'Enter restaurant description',
        'name' => 'description',
        'id' => 'place-description',
    ],
    'image' => [
        'label' => 'Image URL',
        'element' => 'input',
        'type' => 'url',
        'required' => false,
        'pattern' => '/\.(jpg|jpeg|png|gif)$/i',
        'id' => 'place-image',
        'name' => 'image',
    ],
    'price_tier' => [
        'label' => 'Price Tier',
        'element' => 'select',
        'required' => true,
        'name' => 'price_tier',
        'id' => 'price-tier',
    ],
    'price_tier_description' => [
        'label' => 'Price Tier Description',
        'element' => 'input',
        'type' => 'text',
        'required' => false,
        'placeholder' => 'Enter price tier description',
        'name' => 'price_tier_description',
        'id' => 'price_tier_description',
    ],
    'concept' => [
        'label' => 'Concept',
        'element' => 'select',
        'required' => true,
        'name' => 'concept',
        'id' => 'concept',
    ],
    'concept_description' => [
        'label' => 'Concept Description',
        'element' => 'input',
        'type' => 'text',
        'required' => false,
        'placeholder' => 'Enter concept description',
        'name' => 'concept_description',
        'id' => 'concept_description',
    ],
    'diet' => [
        'label' => 'Diet',
        'element' => 'select',
        'required' => false,
        'name' => 'diet',
        'id' => 'diet',
    ],
    'diet_description' => [
        'label' => 'Diet Description',
        'element' => 'input',
        'type' => 'text',
        'required' => false,
        'placeholder' => 'Enter diet description',
        'name' => 'diet_description',
        'id' => 'diet_description',
    ],
];
